require:
  - rubocop-rails

inherit_from:
  - .rubocop_rspec.yml

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'db/**/*'
    - 'bin/**/*'
    - 'spec/**/*'
    - 'node_modules/**/*'
  DisplayCopNames: true

Rails:
  Enabled: true

Rails/FilePath:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'Gemfile'
    - 'config/**/*'
    - 'spec/**/*_spec.rb'
    - 'lib/tasks/*'

Layout/LineLength:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Max: 12

Metrics/CyclomaticComplexity:
  Enabled: false
