version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: .
    environment:
      - EDITOR=vim
      - REDIS_URL=redis://redis:6379
      - WEBPACKER_DEV_SERVER_HOST=webpacker
      - DB_HOST=db
    command: bundle exec rails server -p 3000 -b '0.0.0.0'
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
      - redis
    stdin_open: true
    tty: true

  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - mysql:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: "Asia/Tokyo"

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - redis:/data

  webpacker:
    build: .
    command: ./bin/webpack-dev-server
    ports:
      - '3035:3035'
    depends_on:
      - app
    volumes:
      - .:/app
    environment:
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0

volumes:
  redis:
  mysql:
