version: 2

jobs:
  rubocop:
    docker:
      - image: circleci/ruby:3.0.0-node
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_NAME: test
      - image: circleci/mysql:8.0.26-ram
        command: |
          mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_USER: dbuser
          MYSQL_PASSWORD: dbuser
          MYSQL_ROOT_HOST: '%'
    steps:
      - checkout
      - run:
          name: "create master.key"
          command: echo "${MASTER_KEY}" > config/master.key
      - run:
          name: "bundle install"
          command: bundle install --path vendor/bundle
      - run:
          name: "yarn install"
          command: yarn install
      # MySQLと接続できるまで待ちます
      - run:
          name: "waiting DB start"
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: "initialize DB"
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate
      - run:
          name: rubocop
          command: rubocop

  test:
    docker:
      - image: circleci/ruby:3.0.0-node
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
          DB_NAME: test
      - image: circleci/mysql:8.0.26-ram
        command: |
          mysqld --default-authentication-plugin=mysql_native_password
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_DATABASE: test
          MYSQL_HOST: 127.0.0.1
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_USER: dbuser
          MYSQL_PASSWORD: dbuser
          MYSQL_ROOT_HOST: '%'
    steps:
      - checkout
      - run:
          name: "create master.key"
          command: echo "${MASTER_KEY}" > config/master.key
      - run:
          name: "bundle install"
          command: bundle install --path vendor/bundle
      - run:
          name: "yarn install"
          command: yarn install
      # MySQLと接続できるまで待ちます
      - run:
          name: "waiting DB start"
          command: dockerize -wait tcp://127.0.0.1:3306 -timeout 1m
      - run:
          name: "initialize DB"
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate
      - run:
          name: RSpec
          command: bundle exec rspec

workflows:
  version: 2
  workflows:
    jobs:
      - rubocop
      - test
        - requires:
          - rubocop
