aws:
  access_key_id: <%= Rails.application.credentials.aws[:access_key_id] || 'demmy' %>
  secret_access_key: <%= Rails.application.credentials.aws[:secret_access_key] || 'dummy' %>

db:
  host: <%= Rails.application.credentials.rds[:host] || 'demmy' %>
  database: <%= Rails.application.credentials.rds[:database] || 'dummy' %>
  username: <%= Rails.application.credentials.rds[:username] || 'dummy' %>
  password: <%= Rails.application.credentials.rds[:password] || 'dummy' %>

cloudinary:
  cloud_name: <%= Rails.application.credentials.cloudinary[:cloud_name] || ENV.fetch('CLOUDINARY_CLOUD_NAME', 'dummy') %>
  api_key: <%= Rails.application.credentials.cloudinary[:api_key] || ENV.fetch('CLOUDINARY_API_KEY', 'dummy') %>
  api_secret: <%= Rails.application.credentials.cloudinary[:api_secret] || ENV.fetch('CLOUDINARY_API_SECRET', 'dummy') %>
